### ISSUE TITLE
Tome of water marked incorrectly as prohibited

### ISSUE THREAD

**Issue by Tiamtum** [pwatts6060/runelite-plugins#12]
This came as a surprise to me but the tome of water is actually allowed on Entrana! See exceptions https://oldschool.runescape.wiki/w/Entrana or just go there in game to see for yourself.

**Comment by pwatts6060** [comment]
Thanks for the report, this will be fixed in the next update. If you would like to claim the 100k finders fee, you can reply with your ingame name here. My ingame name is Hi Alchs. @Tiamtum
