### ISSUE TITLE
Star Tier Info - Timer broken after 1.2.0 release

### ISSUE THREAD

**Issue by CreativeTechGuy** [pwatts6060/runelite-plugins#20]
The star timers never show up anymore, regardless of the setting. I assume this is because `InstantEstimator` was removed, which that was the only way that `setTierTicksEstimate` was being set. So now when the plugin tries to get the tier ticks estimate, it is `null`.

**Comment by pwatts6060** [comment]
Thanks, I've put out a fix with hopefully no more issues. Waiting for approval from runelite.
