### ISSUE TITLE
[Entrana] Couldn't take boat with Bandos stole

### ISSUE THREAD

**Issue by pajlada** [pwatts6060/runelite-plugins#21]
Item in question: https://oldschool.runescape.wiki/w/Bandos_stole
Item ID: 12269

This happened in Leagues IV, but I assume the prohibited items list would be the same in the main game.

Thank you!

**Comment by pwatts6060** [comment]
I tested this on the maingame and it does not allow it.

**Comment by pajlada** [comment]
What I'm reporting is that the plugin does not report "Bandos stole" as prohibited on Entrata, while it should.

![image](https://github.com/user-attachments/assets/b1b14258-68af-437e-862b-60bc7a5dd55e)

![image](https://github.com/user-attachments/assets/f2988050-239f-4c54-acfe-fd1b98597797)

![image](https://github.com/user-attachments/assets/6b37944d-26cd-4da6-91cd-a1ed472b37ee)

I made this PR to fix it https://github.com/pwatts6060/runelite-plugins/pull/37
