### ISSUE TITLE
[Entrana] Twitcher's gloves are marked incorrectly as prohibited

### ISSUE THREAD

**Issue by Zebhor** [pwatts6060/runelite-plugins#32]
Twitcher gloves arent prohibited. I do open often easy casket from bird nests on entrana while choping trees and teleport with full lumberjack outfit except axe ofcourse and i can pass easy to island with them.
https://oldschool.runescape.wiki/w/Twitcher%27s_gloves

**Comment by pwatts6060** [comment]
Thanks for the report, this will be fixed in the next update. If you would like to claim the 100k finders fee, you can reply with your ingame name here. My ingame name is Hi Alchs.
