### ISSUE TITLE
[Request]Tick manipulation plugin

### ISSUE THREAD

**Issue by Johndavis2021** [pwatts6060/runelite-plugins#33]
Similar to box traps, could the tick countdown begin when a log gets lit, so you can fm while running(usefull for artefacts). I believe lighting logs after the first one is a 3 tick action

**Comment by pwatts6060** [comment]
Added, awaiting runelite approval.

**Comment by pwatts6060** [comment]
https://github.com/user-attachments/assets/63742d1a-0c9a-460f-8a63-69885cf870a8

Live now @Johndavis2021

**Comment by Johndavis2021** [comment]
> tickfm.mp4 
> Live now @Johndavis2021

thanks alot!
