### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Castro3halo** [pwatts6060/runelite-plugins#39]
Odd request and I suspect it should be another plugin, but could you add this feature to Godwars altars when they are ready to be clicked.

**Comment by pwatts6060** [comment]
> Odd request and I suspect it should be another plugin, but could you add this feature to Godwars altars when they are ready to be clicked. 

Which plugin are you suggesting this for? I believe this already exists as an info box in another plugin though not sure which.

**Comment by Castro3halo** [comment]
You're absolutely right it does, but the great orange/green overlay highlight of this plugin is so much more visually clear rather than 1 of 20 info boxes.

**Comment by pwatts6060** [comment]
This isn't in the scope of the wilderness boss peek plugin and I'm not interested in creating one for the God Wars Dungeon altars. Feel free to use the code and create your own.
