### ISSUE TITLE
Looting bag Value Plugin - Toggleable option to only show how many items are in the looting bag

### ISSUE THREAD

**Issue by MusaKapan** [pwatts6060/runelite-plugins#8]
Hey,

I installed your plugin to help with superglass making in ferox enclave so I pick up the excess glass without having to bank a 2nd time, I was hoping your plugin would have an option to change the overlay to only show how many items are in the bag so I can keep track of when to bank it instead of having to rely on total value or chatbox message saying that the bag is full.

Just throwing it out there :)

Thanks for the work

**Comment by pwatts6060** [comment]
Yes that's a great idea. I can make two toggles for if you want value or free spots and you can have one or both or none on however you like it.

**Comment by JCaedes** [comment]
That would be epic, much appreciated!

**Comment by pwatts6060** [comment]
> That would be epic, much appreciated!

Hey I updated the plugin now with this feature. Please try it out and let me know.
